import type { IAppSetup } from '@models/app-setup.model'
import {
    BREW_CASK,
    BREW_HOME,
    BREW_INSTALL,
    BROW_CASK,
    OPEN_APP_STORE_APP_LINK,
    OPEN_BROWSER_LINK,
} from '../common-commands'

export const APPS: Readonly<IAppSetup[]> = [
    {
        name: 'Alfred',
        group: 'apps',
        description: 'Productivity app, create custom shortcuts and workflows',
        tags: ['productivity'],
        paid: true,
        openUrl: () => BREW_HOME('alfred', true),
        commands: () => [BREW_CASK('alfred')],
    },
    {
        name: 'ChatGPT',
        group: 'apps',
        description: `OpenAI's official ChatGPT desktop app`,
        tags: ['ai'],
        openUrl: () => BREW_HOME('chatgpt', true),
        commands: () => [BREW_CASK('chatgpt')],
    },
    {
        name: 'iBar',
        description: 'Hide menu bar icons and manage them',
        tags: ['productivity'],
        group: 'apps',
        commands: () => [OPEN_APP_STORE_APP_LINK('ibar-menubar-icon-control-tool/id6443843900')],
    },
    {
        name: 'Google Drive',
        description: 'Cloud storage service by Google (password needed)',
        group: 'apps',
        default: true,
        openUrl: () => BREW_HOME('google-drive', true),
        commands: () => [BREW_CASK('google-drive')],
    },
    {
        name: 'Rectangle',
        group: 'apps',
        description: 'Move and resize windows in macOS using keyboard shortcuts',
        tags: ['productivity'],
        openUrl: () => BREW_HOME('rectangle', true),
        commands: () => [BREW_CASK('rectangle')],
    },
    {
        name: 'MonitorControl',
        group: 'apps',
        description: 'Tool to control external monitor brightness and volume',
        openUrl: () => BREW_HOME('monitorcontrol', true),
        commands: () => [BREW_CASK('monitorcontrol')],
    },
    {
        name: 'Slack',
        group: 'apps',
        tags: ['work'],
        openUrl: () => BREW_HOME('slack', true),
        commands: () => [BREW_CASK('slack')],
    },
    {
        name: 'UTM',
        group: 'apps',
        description: 'Virtual machine MacOS',
        openUrl: () => BREW_HOME('utm', true),
        commands: () => [BREW_CASK('utm')],
    },
    {
        name: '1Password',
        group: 'apps',
        tags: ['personal', 'work'],
        paid: true,
        openUrl: () => BREW_HOME('1password', true),
        commands: () => [BREW_CASK('1password')],
    },
    {
        name: 'Cleanshot',
        description: 'Screen recorder and screenshot tool',
        group: 'apps',
        tags: ['productivity'],
        paid: true,
        openUrl: () => BREW_HOME('cleanshot', true),
        commands: () => [BREW_CASK('cleanshot')],
    },
    {
        name: 'Paste',
        description: 'Clipboard manager',
        group: 'apps',
        tags: ['super-user'],
        paid: true,
        openUrl: () => `open https://pasteapp.io/`,
        commands: () => [OPEN_APP_STORE_APP_LINK('paste-endless-clipboard/id967805235')],
    },
    {
        name: 'RCMD',
        description: 'Switch apps instantly using a Hotkey',
        group: 'apps',
        tags: ['super-user'],
        paid: true,
        openUrl: () => `open https://lowtechguys.com/rcmd/`,
        commands: () => [OPEN_APP_STORE_APP_LINK('rcmd-app-switcher/id1596283165')],
    },
    {
        name: 'Amphetamine',
        description: 'Prevent your Mac from sleeping',
        group: 'apps',
        tags: ['super-user'],
        commands: () => [OPEN_APP_STORE_APP_LINK('amphetamine/id937984704')],
    },
    {
        name: 'BetterTouchTool',
        description: 'Customize input devices on macOS, window snapping, etc.',
        group: 'apps',
        tags: ['super-user'],
        paid: true,
        openUrl: () => `open https://folivora.ai/`,
        commands: () => [BREW_CASK('bettertouchtool')],
    },
    {
        name: 'AlDente',
        description: 'Manage and limit maximum charging percentage',
        group: 'apps',
        tags: ['super-user'],
        paid: true,
        openUrl: () => BREW_HOME('aldente', true),
        commands: () => [BREW_CASK('aldente')],
    },
    {
        name: 'TextSniper',
        description: 'Extract and copy text from images (Built-in feature in CleanShot X)',
        group: 'apps',
        tags: ['productivity'],
        paid: true,
        openUrl: () => BREW_HOME('textsniper', true),
        commands: () => [BREW_CASK('textsniper')],
    },
    {
        name: 'Rocket',
        description: 'Emoji shortcuts for faster typing',
        group: 'apps',
        tags: ['productivity'],
        openUrl: () => BREW_HOME('rocket', true),
        commands: () => [BREW_CASK('rocket')],
    },
    {
        name: 'Macs Fan Control',
        description: 'Control fan speed and monitor temperatures',
        group: 'apps',
        openUrl: () => BREW_HOME('macs-fan-control', true),
        commands: () => [BREW_CASK('macs-fan-control')],
        fallbackCommands: () => [BROW_CASK('macs-fan-control')],
    },
    {
        name: 'TinkerTool',
        description: 'Access hidden system settings on macOS',
        group: 'apps',
        tags: ['super-user'],
        openUrl: () => `open https://www.bresink.com/osx/TinkerTool.html`,
        commands: () => [OPEN_BROWSER_LINK('https://www.bresink.com/osx/0TinkerTool/download.php')],
    },
    {
        name: 'Folder Hub',
        description: 'Quickly access your favorite folders from the Notch Bar',
        group: 'apps',
        tags: ['super-user'],
        openUrl: () => `open https://www.finderhub.app/`,
        commands: () => [OPEN_APP_STORE_APP_LINK('folder-hub-file-browser/id6473019059')],
    },
    {
        name: 'Dropover',
        description: 'Drag and drop files between apps with quick actions',
        group: 'apps',
        tags: ['super-user'],
        paid: true,
        openUrl: () => `open https://dropoverapp.com/`,
        commands: () => [OPEN_APP_STORE_APP_LINK('dropover-easier-drag-drop/id1355679052')],
    },
    {
        name: 'WebCatalog',
        description: 'Tool to run web apps like desktop apps',
        group: 'apps',
        tags: ['super-user'],
        openUrl: () => BREW_HOME('webcatalog', true),
        commands: () => [BREW_CASK('webcatalog')],
    },
    {
        name: 'SuperWhisper',
        description: 'AI-powered voice to text transcription tool',
        group: 'apps',
        tags: ['productivity', 'ai'],
        paid: true,
        openUrl: () => BREW_HOME('superwhisper', true),
        commands: () => [BREW_CASK('superwhisper')],
    },
    {
        name: 'Hyperduck',
        description: 'Send links from your iOS & visionOS devices to your Mac',
        group: 'apps',
        tags: ['super-user'],
        openUrl: () => `open https://sindresorhus.com/hyperduck`,
        commands: () => [OPEN_APP_STORE_APP_LINK('hyperduck/id6444667067')],
    },
    {
        name: 'Hovrly',
        description: 'Easily see time zones in your menu bar',
        group: 'apps',
        openUrl: () => BREW_HOME('hovrly'),
        commands: () => [BREW_INSTALL('hovrly')],
    },
    {
        name: 'MeetingBar',
        description: 'Shows upcoming meetings in your menu bar',
        group: 'apps',
        openUrl: () => BREW_HOME('meetingbar', true),
        commands: () => [BREW_CASK('meetingbar')],
    },
    {
        name: 'Reminders MenuBar',
        description: 'Simple menu bar app to view and interact with reminders',
        group: 'apps',
        tags: ['productivity'],
        openUrl: () => BREW_HOME('reminders-menubar', true),
        commands: () => [BREW_CASK('reminders-menubar')],
    },
    {
        name: 'AppCleaner',
        description: 'Uninstall apps and their associated files',
        group: 'apps',
        openUrl: () => BREW_HOME('appcleaner', true),
        commands: () => [BREW_CASK('appcleaner')],
    },
    {
        name: 'Notion',
        group: 'apps',
        tags: ['productivity'],
        openUrl: () => BREW_HOME('notion', true),
        commands: () => [BREW_CASK('notion')],
    },
    {
        name: 'WhatsApp',
        group: 'apps',
        tags: ['personal'],
        openUrl: () => BREW_HOME('whatsapp', true),
        commands: () => [BREW_CASK('whatsapp')],
        fallbackCommands: () => [BROW_CASK('whatsapp')],
    },
    {
        name: 'WhatsApp (legacy)',
        description: 'WhatsApp legacy version',
        group: 'apps',
        openUrl: () => BREW_HOME('whatsapp', true),
        commands: () => [
            BREW_CASK(
                'https://raw.githubusercontent.com/Homebrew/homebrew-cask/2f428f0d63c346637aafd8a8b2f474670c2e42f1/Casks/w/whatsapp.rb',
            ),
        ],
        fallbackCommands: () => [
            BROW_CASK(
                'https://raw.githubusercontent.com/Homebrew/homebrew-cask/2f428f0d63c346637aafd8a8b2f474670c2e42f1/Casks/w/whatsapp.rb',
            ),
        ],
    },
    {
        name: 'Telegram',
        group: 'apps',
        tags: ['personal'],
        openUrl: () => BREW_HOME('telegram', true),
        commands: () => [BREW_CASK('telegram')],
        fallbackCommands: () => [BROW_CASK('telegram')],
    },
    {
        name: 'Vivid',
        group: 'apps',
        description: 'Unlocks the full brightness of your MacBook Pro',
        paid: true,
        openUrl: () => BREW_HOME('vivid', true),
        commands: () => [BREW_CASK('vivid')],
    },
] as const
