import type { IAppSetup } from '@models/app-setup.model'
import { NODE_GLOBAL, NPM_HOME } from '../common-commands'

export const NODE_APPS: Readonly<IAppSetup[]> = [
    {
        name: '@angular/cli',
        group: 'node',
        tags: ['web-engineering'],
        openUrl: () => NPM_HOME('@angular/cli'),
        commands: () => [NODE_GLOBAL('@angular/cli')],
    },
    {
        name: '@nestjs/cli',
        group: 'node',
        tags: ['node-engineering'],
        openUrl: () => NPM_HOME('@nestjs/cli'),
        commands: () => [NODE_GLOBAL('@nestjs/cli')],
    },
    {
        name: 'nx',
        group: 'node',
        tags: ['web-engineering', 'node-engineering'],
        openUrl: () => NPM_HOME('nx'),
        commands: () => [NODE_GLOBAL('nx')],
    },
    {
        name: 'jest',
        group: 'node',
        tags: ['web-engineering', 'node-engineering'],
        openUrl: () => NPM_HOME('jest'),
        commands: () => [NODE_GLOBAL('jest')],
    },
    {
        name: 'ts-jest',
        group: 'node',
        openUrl: () => NPM_HOME('ts-jest'),
        commands: () => [NODE_GLOBAL('ts-jest')],
    },
    {
        name: 'ts-node-dev',
        group: 'node',
        tags: ['node-engineering'],
        openUrl: () => NPM_HOME('ts-node-dev'),
        commands: () => [NODE_GLOBAL('ts-node-dev')],
    },
    {
        name: 'ts-node',
        group: 'node',
        tags: ['node-engineering'],
        openUrl: () => NPM_HOME('ts-node'),
        commands: () => [NODE_GLOBAL('ts-node')],
    },
    {
        name: 'typescript',
        group: 'node',
        tags: ['web-engineering', 'node-engineering'],
        openUrl: () => NPM_HOME('typescript'),
        commands: () => [NODE_GLOBAL('typescript')],
    },
    {
        name: 'nodemon',
        group: 'node',
        tags: ['node-engineering'],
        openUrl: () => NPM_HOME('nodemon'),
        commands: () => [NODE_GLOBAL('nodemon')],
    },
    {
        name: 'cost-of-modules',
        description: 'Full report of all the modules in node_modules and their sizes',
        group: 'node',
        tags: ['web-engineering', 'node-engineering'],
        openUrl: () => NPM_HOME('cost-of-modules'),
        commands: () => [NODE_GLOBAL('cost-of-modules')],
    },
    {
        name: 'npmrc',
        description: 'Manage multiple .npmrc files effortlessly',
        group: 'node',
        tags: ['web-engineering', 'node-engineering', 'devops'],
        openUrl: () => NPM_HOME('npmrc'),
        commands: () => [NODE_GLOBAL('npmrc')],
    },
    {
        name: 'DPDM',
        description: 'A robust static dependency analyzer for your JavaScript and TypeScript projects',
        group: 'node',
        tags: ['web-engineering'],
        openUrl: () => NPM_HOME('dpdm'),
        commands: () => [NODE_GLOBAL('dpdm')],
    },
    {
        name: 'verdaccio',
        group: 'node',
        openUrl: () => NPM_HOME('verdaccio'),
        commands: () => [NODE_GLOBAL('verdaccio')],
    },
    {
        name: 'ttab',
        group: 'node',
        openUrl: () => NPM_HOME('ttab'),
        commands: () => [NODE_GLOBAL('ttab')],
    },
    {
        name: 'gulp-cli',
        group: 'node',
        openUrl: () => NPM_HOME('gulp-cli'),
        commands: () => [NODE_GLOBAL('gulp-cli')],
    },
    {
        name: 'http-server',
        group: 'node',
        openUrl: () => NPM_HOME('http-server'),
        commands: () => [NODE_GLOBAL('http-server')],
    },
    {
        name: 'npkill',
        description: 'List & clear any node_modules directories in your system',
        group: 'node',
        openUrl: () => NPM_HOME('npkill'),
        commands: () => [NODE_GLOBAL('npkill')],
    },
    {
        name: 'prettier',
        group: 'node',
        openUrl: () => NPM_HOME('prettier'),
        commands: () => [NODE_GLOBAL('prettier')],
    },
    {
        name: 'vercel',
        group: 'node',
        openUrl: () => NPM_HOME('vercel'),
        commands: () => [NODE_GLOBAL('vercel')],
    },
] as const
