export enum ReplacementTemplate {
    FULL_NAME = '<FULL_NAME>',
    EMAIL = '<EMAIL>',
    GIT_KEY = '<GIT_KEY>',
    ARTIFACTORY_AUTH = '<ARTIFACTORY_AUTH>',
    CUSTOM_REGISTRY = '<CUSTOM_REGISTRY>',
    CUSTOM_REGISTRY_AUTH = '<CUSTOM_REGISTRY_AUTH>',
}
