on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

name: 📦 Create new release

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Build Packages
              run: |
                  npm install --no-package-lock
                  npm run pack
                  cp ./CHANGELOG.md ./bin/CHANGELOG.md

            - name: Determine file changes
              id: file_changes
              run: |
                  echo "::set-output name=changes::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

            - name: Create Release
              uses: google-github-actions/release-please-action@v3
              with:
                  release-type: 'terraform-module'
                  package-name: 'my-package'
                  path: './bin/cli'
