on:
    push:
        branches:
            - master
            - beta
            - +([0-9])?(.{+([0-9]),x}).x

permissions:
    contents: write
    pull-requests: write
    issues: write
    deployments: write

name: 📦 Create New Release

jobs:
    checks:
        name: ✅ Check for Release
        runs-on: ubuntu-latest
        timeout-minutes: 15

        env:
            HUSKY: 0

        steps:
            - name: 📀 Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: 🧪 Check out repository code
              uses: ./.github/workflows/health-check

    release:
        name: 📦 Release Version
        runs-on: ubuntu-latest
        timeout-minutes: 20
        needs:
            - checks

        env:
            HUSKY: 0

        steps:
            - name: 📀 Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: 🖥️ Setup Env
              uses: ./.github/workflows/install

            - name: 🔨 Build Package
              run: |
                  npm run pack

            - name: 🤐 Archive pack file
              uses: thedoctor0/zip-release@master
              with:
                  path: ./bin/*
                  filename: pack.zip

            - name: Release
              env:
                  # This is required to make semantic-release work with GitHub Actions
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  GIT_AUTHOR_NAME: github-bot
                  GIT_AUTHOR_EMAIL: github-bot@gmail.com
                  GIT_COMMITTER_NAME: github-bot
                  GIT_COMMITTER_EMAIL: github-bot@gmail.com
              run: |
                  npx semantic-release
